apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagenet-annotations-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-ceph-block
