apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atharv-rwo-scratch-2ti
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Ti
